Fix lot attribute parsing
jcornaz/beancount-parser pull request #20
Opened 2023-01-23 00:53 UTC by jeffwheeler

Previously, attributes were not parsed carefully, so dates and labels could not be extracted. Also, empty attributes (`{}`) would fail to parse. (Empty cost fields are valid when performing reductions, see [How Inventories Work](https://beancount.github.io/docs/how_inventories_work.html) in the Beancount documentation.)

This commit fixes the parsing, while preserving the existing API.

2023-01-23 09:56 UTC, jcornaz requested changes
Thank you very much!

As the tests are focused on fixing the bug in `Posting::cost`, I'd rather, keep `Posting::lot_attributes` private for now, and have this PR be a bug-fix only (no new features).

We may of course follow up with the `lot_attributes` feature, by making that member public and writing a couple of tests for it.

2023-01-23 09:56 UTC, jcornaz commented on src/transaction/posting.rs
> +        assert!(posting.lot_attributes().is_none());
```suggestion
        assert!(posting.cost().is_none());
        assert!(posting.lot_attributes().is_none());
```

2023-01-23 09:56 UTC, jcornaz commented on src/transaction/posting.rs
> +pub struct LotAttributes<'a> {
keep it private for now,

```suggestion
struct LotAttributes<'a> {
```

2023-01-23 09:56 UTC, jcornaz commented on src/transaction/posting.rs
> +    pub fn lot_attributes(&self) -> Option<&LotAttributes<'a>> {
keep it private for now

```suggestion
    fn lot_attributes(&self) -> Option<&LotAttributes<'a>> {
```

2023-01-23 19:21 UTC, jcornaz approved these changes
Thank you very much for the bug report and bug fix.

I made tiny adjustments (removed the new public members, and addressed clippy warnings) and will merge this PR, so that I can cut a patch release.

You may re-add the public `lot_attributes` in a follow-up PR if you want.

Thanks again.

2023-01-23 19:27 UTC, merged

2023-01-24 05:56 UTC, jeffwheeler commented
Looks good, thanks for the follow-up commits 🙂